### ISSUE TITLE
Failure handling user response error after clicking a notification.

### ISSUE THREAD

**Issue by TannerYoung** [noinskit/flutter_local_notifications#1]
Hey there!

Ran into a new issue and was curious if you've come across it. This is after a notification appears and I click on an action which has a callback set up. The callback never gets triggered.

```
I/NotifActionReceiver(12270): NotificationActionReceiver received: {"autoCancel":true,"body":"...","category":{"actions":[{"identifier":"decline","title":"Decline"},{"identifier":"accept","title":"Accept"}],"identifier":"AcceptDecline"},"categoryIdentifier":"AcceptDecline","channelAction":"CreateIfNotExists","channelDescription":"Notification Channel Desc","channelId":"Notification Channel Id","channelName":"Notification Channel","channelShowBadge":true,"enableLights":false,"enableVibration":true,"groupAlertBehavior":0,"id":1398369959,"importance":5,"indeterminate":false,"maxProgress":0,"payload":"<payload>"}","playSound":true,"priority":1,"progress":0,"showProgress":false,"style":"Default","styleInformation":{"type":"DefaultStyleInformation","htmlFormatBody":false,"htmlFormatTitle":false},"title":"<title>"}
I/flutter (12270): Signalling notificationActionQueue being initialized...
I/flutter (12270): Processing notification action data: {payload: <payload>, categoryIdentifier: AcceptDecline, actionIdentifier: accept}
I/flutter (12270): Enqueuing notification action: {"categoryIdentifier":"AcceptDecline","actionIdentifier":"accept","payload":"<payload>"}
I/NotifActionReceiver(12270): Success processing enqueue!
I/flutter (12270): Notification action data pieces to process: [{"categoryIdentifier":"AcceptDecline","actionIdentifier":"accept","payload":"<payload>"}]
I/flutter (12270): Failure handling user response. Invalid argument(s): The source must not be null
I/flutter (12270): Notification action data pieces to process: []
```

Not sure where the "The source must not be null" is coming from, can't seem to find anything in the codebase that matches that or the "user response" string, and googling didn't bring up anything except people asking about adb logging for unrelated issues.

This is for Android, and after setting the plugin registrant as follows (not 100% sure if related, still trying to diagnose when this was introduced, because I know at some point this was working):

```
    FlutterLocalNotificationsPlugin.setPluginRegistrant(new PluginRegistrantCallback() {
      @Override
      public void registerWith(PluginRegistry registry) {
        SharedPreferencesPlugin.registerWith(registry.registrarFor("io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin"));
      }
    });
```

**Comment by noinskit** [comment]
Setting up the plugin registrant looks okay. And I'm quite sure it works, because your log indicates that the plugin successfully fetched some data from SharedPreferences.

I can't reproduce your error yet. I tried injecting this specific action data (`{"categoryIdentifier":"AcceptDecline","actionIdentifier":"accept","payload":"<payload>"}`) into the example app and it worked.

On the bright side - I think this error is coming from the Dart SDK, specifically `integers_patch.dart`, as if something called `int.parse(null)` (I guess either directly or as part of deserialization of something).

If you're sure that this is not coming from your code on the receiving side of the action queue, any chance you could try to set a breakpoint in `_getNextDataToProcess()` in `notification_action_queue.dart` and then see where it throws?

**Comment by TannerYoung** [comment]
Sorry for the delayed response I've been out of town. Not sure what the issue was but I'm sure it was something to do with my setup not this fork, closing.
